### ISSUE TITLE
Set up Let's Encrypt on http://diyhpl.us/wiki/

### ISSUE THREAD

**Issue by michaelfolkson** [kanzure/diyhpluswiki#63]
This has been on my to do list for a while, to at least enquire about it if not do it myself. I haven't successfully set Let's Encrypt (https://letsencrypt.org/) up before. When I previously tried there were problems specific to my domain registrar. Is there anything particular I should know specific to http://diyhpl.us/wiki/ or would you expect this to be relatively pain-free?

**Comment by kanzure** [comment]
```
bung@richardiv:~$ openssl s_client -connect diyhpl.us:443 -servername diyhpl.us 2>/dev/null </dev/null | grep issuer
issuer=C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
```

http://gnusha.org/logs/2019-11-26.log

**Comment by michaelfolkson** [comment]
Sorry, being stupid.... The description of the repo just needs updating to say https instead of http

> a wiki for do-it-yourself biohacking, open source hardware and transhuman tech http://diyhpl.us/wiki

**Comment by kanzure** [comment]
Oh, sure. Done. Thanks.
