### ISSUE TITLE
Sign-ups broken

### ISSUE THREAD

**Issue by ysangkok** [kanzure/diyhpluswiki#9]
The action attribute of the form tag points to a URL which serves a 404.

Also weird is the fact that  https://secure.diyhpl.us doesn't serve the same as https://www.secure.diyhpl.us

**Comment by kanzure** [comment]
In the mean time, you can submit merge requests through github instead. Same git repository.

**Comment by ysangkok** [comment]
Seems like this is stale since both of these urls are now unavailble.
